server:
  servlet:
    context-path: /store-api
  port: 8080

spring:
  application:
    name: 'store'

provider:
  url: http://provider/provider-api

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
